Traceback (most recent call last):
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import geostatspy.GSLIB as GSLIB          # GSLIB utilies, visualization and wrapper
import geostatspy.geostats as geostats    # GSLIB methods convert to Python        
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeostatspy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mGSLIB[39;00m [38;5;28;01mas[39;00m [38;5;21;01mGSLIB[39;00m          [38;5;66;03m# GSLIB utilies, visualization and wrapper[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeostatspy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgeostats[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgeostats[39;00m    [38;5;66;03m# GSLIB methods convert to Python        [39;00m

File [1;32m~\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\geostatspy\GSLIB.py:30[0m
[0;32m     28[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m  [38;5;66;03m# for DataFrames[39;00m
[0;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m [38;5;28;01mimport[39;00m signal
[1;32m---> 30[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtqdm[39;00m [38;5;28;01mimport[39;00m tqdm [38;5;66;03m# progress bar[39;00m
[0;32m     32[0m [38;5;66;03m# Hard coded image file output[39;00m
[0;32m     33[0m image_type [38;5;241m=[39m [38;5;124m"[39m[38;5;124mtif[39m[38;5;124m"[39m

[1;31mModuleNotFoundError[0m: No module named 'tqdm'

